import json
from crew import crew

def main():
    # Sample alert payload as per requirement
    alert_payload = {
        "endpoint": "/payments",
        "error_rate": 0.35,
        "latency_p99": 3200,
        "status_codes": {"500": 1200, "502": 300},
        "affected_users": 15000
    }

    print("Execution Started: PD API Health Check Warroom")
    print("-" * 50)
    
    try:
        # Running the crew
        result = crew.kickoff(inputs={"alert_payload": json.dumps(alert_payload)})

        # Prepare readable output
        output_file = "final_incident_report.md"
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# Automated Incident Response Report\n\n")
            f.write("## Triggered Alert Data\n")
            f.write(f"```json\n{json.dumps(alert_payload, indent=4)}\n```\n\n")
            f.write("## CrewAI Analysis Results\n")
            f.write(str(result))
            f.write("\n\n---\n")
            f.write("*Report generated by Incident Response CrewAI.*")

        print(f"Success! Detailed results stored in: {output_file}")
        print("-" * 50)
        print("Summary of findings:")
        print(str(result))
        
    except Exception as e:
        import traceback
        with open('error_log.txt', 'w', encoding='utf-8') as f:
            f.write(traceback.format_exc())
        print(f"Error during execution: written to error_log.txt")

if __name__ == "__main__":
    main()
